import { AnimeFilter } from "../types";


export const DEFAULT_FILTERS: AnimeFilter = {
  country: null,
  season: null,
  sort: 0,
  source: null,
  studio: null,
  age_ratings: [],
  category_id: null,
  end_year: null,
  episode_duration_from: null,
  episode_duration_to: null,
  episodes_from: null,
  episodes_to: null,
  genres: [],
  is_genres_exclude_mode_enabled: false,
  profile_list_exclusions: [],
  start_year: null,
  status_id: null,
  types: [],
}as const;

export const ONGOING_FILTERS: AnimeFilter = {
  country: null,
  season: null,
  sort: 0,
  source: null,
  studio: null,
  age_ratings: [],
  category_id: null,
  end_year: null,
  episode_duration_from: null,
  episode_duration_to: null,
  episodes_from: null,
  episodes_to: null,
  genres: [],
  is_genres_exclude_mode_enabled: false,
  profile_list_exclusions: [],
  start_year: null,
  status_id: 2,
  types: [],
}as const ; 

export const ANNOUNCEMENTS_FILTERS: AnimeFilter = {
  country: null,
  season: null,
  sort: 0,
  source: null,
  studio: null,
  age_ratings: [],
  category_id: null,
  end_year: null,
  episode_duration_from: null,
  episode_duration_to: null,
  episodes_from: null,
  episodes_to: null,
  genres: [],
  is_genres_exclude_mode_enabled: false,
  profile_list_exclusions: [],
  start_year: null,
  status_id: 3,
  types: [],
} as const;

export const COMPLETED_FILTERS: AnimeFilter = {
  country: null,
  season: null,
  sort: 0,
  source: null,
  studio: null,
  age_ratings: [],
  category_id: null,
  end_year: null,
  episode_duration_from: null,
  episode_duration_to: null,
  episodes_from: null,
  episodes_to: null,
  genres: [],
  is_genres_exclude_mode_enabled: false,
  profile_list_exclusions: [],
  start_year: null,
  status_id: 1,
  types: [],
} as const;

export const MOVIES_FILTERS: AnimeFilter = {
  country: null,
  season: null,
  sort: 0,
  source: null,
  studio: null,
  age_ratings: [],
  category_id: 2,
  end_year: null,
  episode_duration_from: null,
  episode_duration_to: null,
  episodes_from: null,
  episodes_to: null,
  genres: [],
  is_genres_exclude_mode_enabled: false,
  profile_list_exclusions: [],
  start_year: null,
  status_id: null,
  types: [],
} as const; 